name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE: 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # install deps
      - run: pnpm install --frozen-lockfile

      # turbo cache
      - uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: turbo-cache-${{ runner.os }}

      # code check
      - run: pnpm turbo build:scss typecheck

      # test
      - run: pnpm test

      # build for greasyfork
      - run: pnpm build:real-build
        env:
          MINIFY: 'false'

      # build minified version
      - run: pnpm build:real-build
        env:
          MINIFY: 'true'

      #
      # commit to release branch, orphan commit
      #
      - run: mkdir dist-release-branch && touch ./dist-release-branch/bilibili-gate.user.js
      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-release-branch
          force_orphan: true

      #
      # commit to release branch
      #
      - run: cp README.md ./dist
      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: release
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: false

      # release with changelog
      - run: pnpx changeloggithub@0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # release assets
      - name: Upload *.user.js to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.user.js
